version: '3'
services:
  petclinic:
    stdin_open: true
    tty: true
    working_dir: /home/spring-petclinic
    image: dockercontainervm/petclinic-spring:latest
    container_name: petclinic
    expose:
    - 8080
    ports:
    - "3000:8080"
    environment:
    - PATH=/root/workspace/maven/apache-maven-3.5.4/bin:/root/workspace/java/jdk1.8.0_181/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    entrypoint: ./run-services-docker.sh
